_target_: lerobot.robots.so100_follower.config_so100_follower.SO100FollowerConfig
port: /dev/ttyACM1
id: my_awesome_follower_arm
cameras:
  main: 
    _target_: lerobot.cameras.opencv.OpenCVCameraConfig
    index_or_path: 
      _target_: pathlib.Path
      _args_: ["/dev/video4"]
    width: 320
    height: 240
    fps: 30
